# fly.toml app configuration file
# For a backend-only Python/Flask application

app = 'spotify-mood-player-backend' # IMPORTANT: Use your actual Fly.io app name here
primary_region = 'lax' # Or your preferred Fly.io region

[build]
  dockerfile = "Dockerfile" # Points to the Dockerfile in your project root

[[services]]
  internal_port = 5001 # This MUST match the port Gunicorn (and your [env].PORT) is configured to use inside the container.
  protocol = "tcp"
  processes = ["app"] # This refers to the CMD in your Dockerfile.

  # HTTP health check for your Flask application.
  # Your Flask app should have an endpoint at this path that returns a 2xx status.
  [[services.http_checks]]
    interval = "15s"    # How often to check health.
    timeout = "5s"      # How long to wait for a response.
    grace_period = "20s" # How long to wait after a machine starts before performing the first check. Increase if your app starts slowly.
    method = "GET"
    path = "/api/health" # IMPORTANT: Ensure your Flask app has this endpoint.
    # For example, in backend/app.py:
    # @app.route('/api/health', methods=['GET'])
    # def health_check():
    #     return jsonify({"status": "healthy"}), 200

  # Public-facing ports that route traffic to your service's internal_port.
  [[services.ports]]
    handlers = ["http"]
    port = 80 # External HTTP port
    force_https = true # Redirect HTTP to HTTPS

  [[services.ports]]
    handlers = ["tls", "http"] # Handles HTTPS termination and also HTTP for the forced redirect.
    port = 443 # External HTTPS port

# Optional: Define machine size. Adjust based on your application's needs.
[vm]
  memory = "1gb" 
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024