# fly.toml app configuration file generated for mood-player-backend on 2025-06-04T16:39:47-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mood-player-backend'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  FLASK_ENV = 'production'
  PORT = '8080'
  GEVENT_NOWAIT_AFTER_FORK = '1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2

[processes]
  app = "gunicorn --worker-class gevent --workers 4 --bind 0.0.0.0:8080 app:app"
