# fly.toml app configuration file generated for spotify-mood-mysql on 2025-05-29T05:21:17-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spotify-mood-mysql'
primary_region = 'lax'

[build]
  image = 'mysql:8'



[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  protocol = "tcp"
  internal_port = 3306
  
  [[services.ports]]
    port = 3306
    handlers = ["tls"]

[metrics]
  port = 9091
  path = "/metrics"

[[mounts]]
  source = "mysql_data"
  destination = "/var/lib/mysql"

[checks]
  [checks.mysql]
    port = 3306
    type = "tcp"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
