name: Deploy Backend to AWS Lambda

on:
  push:
    paths:
      - 'backend/**'
      - '!backend/README.md'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Serverless Framework
        uses: serverless/serverless-actions/setup-serverless@v1
        