
name: Fly Deploy Backend

on:
  push:
    branches:
      - main  
    paths:
      - 'backend/**' # Only run on changes in the backend directory
      - 'Dockerfile'   
      - 'fly.toml'     
      - '.github/workflows/fly-deploy.yml' 

jobs:
  deploy:
    name: Deploy Backend to Fly
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}